remote_theme: thelehhman/plainwhite-jekyll
plainwhite:
  name: Artemy Skrebkov
  tagline: Developer
  date_format: "%b %-d, %Y"

  social_links:
    github: ArtemSkrebkov
    linkedIn: in/artemy-skrebkov-a63227180
